[package]
name = "test-cargo-dependabot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.172"
strum = ">= 0.13, < 0.27"
syn = "1.0.99"
